#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# Help-helper utility
#

. "$(dirname "$(readlink -f "$0")")/init.sh" || exit "$?"

lib helpy print-subcommands "$(this-cmd-name)"
