#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# Help-helper utility
#

. "$(dirname "$(readlink -f "$0")")/init.sh" || exit "$?"

error=0
if (( $# != 0 )) && [[ $1 =~ [^-] ]]; then
    error-msg "Unknown subcommand: $1"
    error-msg
    error=1
fi

lib helpy print-subcommands "$(this-cmd-name)"
exit "${error}"
