#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# This is an example script.
#

. "$(dirname "$(readlink -f "$0")")/init.sh" || exit "$?"
# use-lib 'lib-name'

info-msg "Hello from $(this-cmd-name)!"

if (( $# == 0 )); then
    info-msg 'No arguments.'
else
    info-msg 'Arguments:'
    info-msg --exec printf '  %q\n' "$@"
fi

if [[ $# != 0 ]]; then
    info-msg 'Self-call but with no arguments:'
    lib do-something
    info-msg 'Done with self-call.'
    info-msg
fi

info-msg 'Other call:'
lib sub hello called from "$(this-cmd-name)"
info-msg 'Done with other call.'
