#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# This is an example script.
#

. "$(dirname "$(readlink -f "$0")")/../init.sh" || exit "$?"
# use-lib 'lib-name'

info-msg "Hello from $(this-cmd-name)!"
