#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# Prerequisite checks for this unit.
#

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"

if ! which openssl >/dev/null 2>&1; then
    error-msg 'Missing `openssl` binary.'
    return 1
fi

if ! which ssh-keygen >/dev/null 2>&1; then
    error-msg 'Missing `ssh-keygen` binary.'
    return 1
fi
