#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# Prerequisite checks for this sublibrary.
#

. "$(dirname "$(readlink -f "$0")")/init.sh" || exit "$?"

# TODO
info-msg '#### HELLO FROM BASHY-BASICS PREREQ!'
