#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage $'
    ${name} <json-value>

    Prints the length of the given JSON value, per the `jq` length rules.

    ${help}
'

# Want help?
opt-action --call='{ usage; exit }' help/h

# JSON value.
positional-arg --required --var=value json-value

process-args "$@" || usage --short


#
# Main script
#

exec jq --null-input --argjson value "${value}" '$value | length'
