#!/bin/bash
#
# Copyright 2022 the Bashy-lib Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License, Version 2.0.
# Details: <http://www.apache.org/licenses/LICENSE-2.0>

# Load the helper libraries.
. "$(dirname "$(readlink -f "$0")")/init.sh" || exit "$?"

#
# Argument parsing
#

function usage {
    lib helpy print-usage --name="$(this-cmd-name)" "$@" $'
    ${name} <json-value>

    Prints the length of the given JSON value, per the `jq` length rules.

    ${name} [--help | -h]

    Displays this message.
    '
}

# Want help?
opt-action --call='{ usage; exit }' help/h

# JSON value.
positional-arg --required --var=value json-value

process-args "$@" || call-then-exit "$?" usage --short


#
# Main script
#

exec jq --null-input --argjson value "${value}" '$value | length'
