#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} <string> ...

    Prints a series of zero or more JSON strings, representing the arguments in
    order.
'

# Strings to convert
rest-arg --var=values string

process-args "$@" || exit "$?"


#
# Main script
#

if (( ${#values[@]} == 0 )); then
    # No need to do anything.
    exit
fi

# Note: Unfortunately, because `jq` v1.6 or earlier doesn't actually do the
# usual shell command behavior of not attempting to interpret things that look
# like options but are positioned after non-option arguments, it's not actually
# possible to use `--args` because the intended arguments could end up
# interpreted as options.

jqArgs=(--null-input)

expr=''
for n in "${!values[@]}"; do
    jqArgs+=(--arg "a${n}" "${values[n]}")
    if (( n != 0 )); then
        expr+=','
    fi
    expr+='$a'"${n}"
done

exec jq "${jqArgs[@]}" "${expr}"
