#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage $'
    ${name} [<opt> ...] [--] [<assignment> ...] [--] [<jq-expression> ...]

    Constructs and prints one or more JSON values from variable assignments
    passed into an expression evaluated by `jq` either with `--null-input` (by
    default) or as a usual pipeline over input values. If no expression is
    given, it is taken to be `.`, which will end up formatting the input as
    implied/specified by the output option.

    The <jq-expression> arguments are concatenated together (separated by
    spaces) to form the final expression to be evaluated.

    <assignment>
      <name>:<type>[:file]=<value> -- Assign `$name` to be the indicated value.
        With optional `:file`, <value> is interpreted as a filesystem path, and
        the so-named file is read; without it, <value> is just taken to be the
        text to be interpreted and assigned. <type> determines the interpretation:

        `json` -- Interpret <value> as JSON text.
        `raw` -- Interpret <value> as a raw string. This is the default if
          type is not specified.

    --input=<style>
      `none` -- Do not read from stdin. This is the default.
      `raw[:slurp]` -- Read newline-terminated lines of text from stdin to form
         pipeline input. With `:slurp`, produces an array of all lines as the
         sole input.
      `raw0[:slurp]` -- Read NUL-terminated (`\\0`) strings of text from stdin
         to form pipeline input. With `:slurp`, produces an single array of all
         strings as the sole input. Note: This tolerates a missing NUL from the
         end of input; it does _not_ produce an extra blank element with NUL at
         the end of input.
      `read` -- Read JSON values from stdin individually to form pipeline input.
      `slurp` -- Read a series of JSON values from stdin into a single array,
        producing a single-value pipeline input.
    --output=<style>
      `compact` -- Output in compact (single line) JSON form.
      `json` -- Output in multiline JSON form. This is the default.
      `lines` -- Output each item as a single line. Similar to `raw`, except
        that strings with newlines or CRs in them get treated as non-raw so as
        to maintain the guarantee of item-per-line.
      `none` -- Suppress all non-error output.
      `raw` -- Output strings as newline-terminated raw text (and other values
        as `compact`).
      `raw0` -- Output strings as NUL-terminated (`\\0`) raw text (and other
        values as `compact`).
      `words` -- Like `lines`, except that the guarantee is a word per line.
        As such, strings containing whitespace get treated as non-raw.

    ${help}
'

# Want help?
opt-action --call='{ usage; exit }' help/h

# Input style.
opt-value --var=inputStyle --init=none \
    --enum='none raw raw:slurp raw0 raw0:slurp read slurp' \
    input

# Output style.
opt-value --var=outputStyle --init=json \
    --enum='compact json lines none raw raw0 words' output

# List of variable assignments, as parallel arrays of type, name, and value.
varTypes=()
varNames=()
varValues=()

# Value construction expression.
valueExpression=''

rest-arg --call=parse-rest jval-exprs
function parse-rest {
    # Parse assignments.
    while (( $# > 0 )); do
        local arg="$1"
        if [[ ${arg} == '--' ]]; then
            shift
            break
        fi

        [[ ${arg} =~ ^([_a-zA-Z0-9]+)(:[a-z]+(:[a-z]+)?)?=(.*)$ ]] \
        || break

        varNames+=("${BASH_REMATCH[1]}")
        varValues+=("${BASH_REMATCH[4]}")

        local varType="${BASH_REMATCH[2]}"
        if [[ ${varType} == '' ]]; then
            varType='raw'
        elif [[ ${varType} == ':file' ]]; then
            varType='raw:file'
        else
            varType="${varType:1}" # `:1` to drop the initial `:`.
        fi

        varTypes+=("${varType}")

        shift
    done

    # Report an error if the next argument loosely looks like an assignment,
    # because it is probably a bug in the caller.
    if [[ $1 =~ ^[-_:a-zA-Z0-9]+= ]]; then
        local problem="${BASH_REMATCH[0]}"
        error-msg 'Invalid assignment left-hand side:'
        error-msg "  ${problem}"
        return 1
    fi

    # Construct the value expression from the remaining arguments.
    if (( $# == 0 )); then
        valueExpression='.'
    else
        valueExpression="$*"
    fi
}

process-args "$@" || usage --short


#
# Main script
#

jqArgs=()

case "${inputStyle}" in
    none)
        jqArgs+=('--null-input')
        ;;
    raw)
        jqArgs+=('--raw-input')
        ;;
    raw:slurp)
        jqArgs+=('--raw-input' '--slurp')
        rawSlurpHelper='
            split("\n")
            |
            if .[length - 1] == ""
                then .[:length - 1]
                else .
            end'
        valueExpression="${rawSlurpHelper} | (${valueExpression})"
        ;;
    raw0)
        jqArgs+=('--raw-input' '--slurp')
        raw0Helper='sub("\u0000$"; "") | split("\u0000") | .[]'
        valueExpression="${raw0Helper} | (${valueExpression})"
        ;;
    raw0:slurp)
        jqArgs+=('--raw-input' '--slurp')
        raw0SlurpHelper='sub("\u0000$"; "") | split("\u0000")'
        valueExpression="${raw0SlurpHelper} | (${valueExpression})"
        ;;
    read)
        : # No additional arguments needed.
        ;;
    slurp)
        jqArgs+=('--slurp')
        ;;
esac

case "${outputStyle}" in
    compact)
        jqArgs+=('--compact-output')
        ;;
    lines)
        jqArgs+=('--raw-output' '--compact-output')
        lineHelper='
            if type == "string" and test("[\n\r]"; "m")
                then (. | @json)
                else .
            end'
        valueExpression="(${valueExpression}) | ${lineHelper}"
        ;;
    raw)
        jqArgs+=('--raw-output' '--compact-output')
        ;;
    raw0)
        jqArgs+=('--join-output' '--compact-output')
        raw0Helper='. + "\u0000"'
        valueExpression="(${valueExpression}) | ${raw0Helper}"
        ;;
    words)
        jqArgs+=('--raw-output' '--compact-output')
        wordHelper='
            if type == "string" and test("[ \n\r\t]"; "m")
            then (. | @json)
            else .
            end'
        valueExpression="(${valueExpression}) | ${wordHelper}"
        ;;
esac

for i in "${!varNames[@]}"; do
    varName="${varNames[i]}"
    varType="${varTypes[i]}"
    varValue="${varValues[i]}"

    if [[ ${varType} =~ ^([^:]+):file$ ]]; then
        varType="${BASH_REMATCH[1]}"
        if [[ ! -r "${varValue}" ]]; then
            error-msg "Not readable: ${varValue}"
            exit 1
        fi
        varValue="$(cat "${varValue}")" || exit "$?"
    fi

    case "${varType}" in
        json)
            jqArgs+=('--argjson')
            ;;
        raw)
            jqArgs+=('--arg')
            ;;
        *)
            error-msg "Unrecognized variable type: ${varType}"
            exit 1
            ;;
    esac

    jqArgs+=("${varName}" "${varValue}")
done

# Note: `jq` doesn't recognize `--` as an end-of-options sign, but generally
# speaking there's no ambiguity between a valid `jq` option and actually useful
# program text. Nonetheless, we prepend an extra space if the program begins
# with a dash, just in case the user of this script passed in something wacky.
if [[ ${valueExpression} =~ ^- ]]; then
    valueExpression=" ${valueExpression}"
fi

jqArgs+=("${valueExpression}")

if [[ ${outputStyle} == 'none' ]]; then
    exec jq "${jqArgs[@]}" >/dev/null
else
    exec jq "${jqArgs[@]}"
fi
