#!/bin/bash

# Figure out the symlink-resolved program name and directory.
cmdName="$(readlink -f "$0")" || exit "$?"
cmdDir="${cmdName%/*}"
cmdName="${cmdName##*/}"
baseDir="${cmdDir%/*}"

# TODO: Check for version of Node.

# Note: `--no-warnings` suppresses Node's built-in warning printer, which we do
# because this program includes its own warning handler.
node --no-warnings "${baseDir}/code/index.js"
