#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} [<opt> ...]

    Makes a new temporary directory, and prints out the path to it. The final
    component name starts with the prefix `tmp-` unless overridden by an option.

    --prefix=<string>
      Prefix to use instead of `tmp-`. Note: If you want a `-` at the end, you
      need to include it.
'

# Prefix.
opt-value --var=prefix --default='tmp-' prefix

process-args "$@" || exit "$?"


#
# Main script
#

# Use the env variable if set, or `/tmp` if not. And canonicalize it.
tmpDir="$(readlink -f -- "${TMPDIR:-/tmp}")" || exit "$?"

path=''
while true; do
    path="${tmpDir}/$(lib . name --prefix="${prefix}")"
    if [[ ! -e ${path} ]]; then
        break
    fi
done

mkdir "${path}"
echo "${path}"
