#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage $'
    ${name} [<opt> ...] [--] <command>

    Makes a new temporary directory, and prints out the path to it.

    ${name} [--help | -h]

    Displays this message.
'

# Want help?
opt-action --call='{ usage; exit }' help/h

process-args "$@" || usage --short


#
# Main script
#

# Use the env variable if set, or `/tmp` if not. And canonicalize it.
tmpDir="$(readlink -f "${TMPDIR:-/tmp}")" || exit "$?"

path=''
while true; do
    path="${tmpDir}/$("$(this-cmd-dir)/name")"
    if [[ ! -e ${path} ]]; then
        break
    fi
done

mkdir "${path}"
echo "${path}"
