#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# This is an example top-level script dispatcher.
#

. "$(dirname "$(readlink -f "$0")")/lib/bashy-core/init.sh" || exit "$?"


#
# Argument parsing
#

function usage {
    lib helpy print-usage $'
    ${name} <subcommand> ... [<opt> ...] [--] [<arg> ...]
      Does something exemplar. <opt>s and <arg>s depend on the specific
      subcommand.

    ${name} [--help | -h]
      Displays this message.
    '

    exit "$@"
}

# Want help?
opt-action --call='{ usage }' help/h

# The actual command arguments.
rest-arg --var=args args

process-args "$@" || usage "$?"


#
# Main script
#

# You can list any number of sub-library names in place of `my-project` below.
lib --libs=my-project --quiet "${cmdName}" "${args[@]}"
exitCode="$?"

if (( exitCode == 127 )); then
    error-msg "Command not found: ${cmdName}"
    exit 1
fi

exit "${exitCode}"
