#!/bin/bash
#
# Copyright 2022-2023 the Lactoserv Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage $'
    ${name} [<opt> ...]

    Builds the project.

    --clean
      Do a clean build.
    --make-distro
      Create a distribution tarball.
    --out=<dir>
      Directory where built output goes. Defaults to `out` directly under the
      main product directory.

    ${help}
'

# Want help?
opt-action --call='{ usage; exit }' help/h

# Clean build?
opt-toggle --var=doClean clean

# Make a distribution tarball?
opt-toggle --var=doDistro make-distro

# Built output directory.
opt-value --var=outDir out

process-args "$@" || usage --short


#
# Helper functions
#

# Sets up the output directory.
function set-up-out-dir {
    local extraOpts=()
    if (( doClean )); then
        extraOpts=(--remove)
    fi

    lib out-dir \
        --out="${outDir}" --create --print "${extraOpts[@]}"
}


#
# Main script
#

srcDir="$(base-dir)/src"
etcDir="$(base-dir)/etc"
outDir="$(set-up-out-dir)"

extraOpts=()
if (( doDistro )); then
    extraOpts+=(--make-distro)
fi

lib build-js-project --out="${outDir}" "${extraOpts[@]}" lactoserv \
|| exit "$?"

progress-msg
progress-msg 'Build complete!'
