#!/bin/bash
#
# Copyright 2022-2024 the Lactoserv Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} [<opt> ...] [<target> ...]

    Does various development-time actions for the project. By default, this
    executes the target `build` unless otherwise overridden by options.

    Available targets:
    `build` -- Do a full build.
    `clean` -- Remove the built-output directory.
    `distro` -- Build a distro tarball.
    `lint` -- Run the linter.
    `run` -- Run the system, with the standard example config in
      `etc/example-setup`.

    --lint[]=<arg> ...
      Arguments to pass to the system when `lint`ing. This makes the default
      target be `lint`.
    --out=<dir>
      Directory where built output goes. Defaults to `out` directly under the
      main product directory.
    --run[]=<arg> ...
      Arguments to pass to the system when `run`ning. This makes the default
      target be `run`.
'

# Make a distribution tarball?
opt-toggle --var=doDistro make-distro

# Built output directory.
opt-value --var=outDir out

# Arguments for linting.
opt-multi --var=lintArgs lint

# Arguments for running.
opt-multi --var=runArgs run

# Build targets.
rest-arg --var=targets --filter='/^[a-z]+/' target

process-args "$@" || exit "$?"


#
# Build targets
#

# Target: `build`
function target-build {
    # Run in a subshell so that `env-minimize` has no lasting effect.
    (
        true \
        && env-minimize \
        && lib node-project build-main-module \
            --out="${outDir}" --modules-dirs="${srcDir}" \
            --runner-script=run --runner-versions[]='20 21' \
            lactoserv
    )
}

# Target: `clean`
function target-clean {
    rm -rf "${outDir}"
    mkdir -p "${outDir}"
}

# Target: `distro`
function target-distro {
    satisfy-target build \
    || return "$?"

    progress-msg 'Making distribution tarball...'

    lib buildy make-distro --out="${outDir}" "${outDir}/lactoserv"
}

# Target: `lint`
function target-lint {
    : # Nothing to do. See below for where the linter is actually run.
}

# Target: `run`
function target-run {
    # See below for where the system is actually run. What we do here is just
    # ensure that it's built.
    if [[ ! -x ${outRun} ]]; then
        satisfy-target build \
        || return "$?"
    fi
}


#
# Main script
#

# Make a temporary directory, and arrange for its deletion upon exit.
tmpDir="$(lib tempy mkdir)" || exit "$?"
trap "rm -rf \"${tmpDir}\"" EXIT

include-lib buildy-help --tmp-dir="${tmpDir}"

srcDir="$(base-dir)/src"
outDir="$(set-up-out-dir --out="${outDir}")" || exit "$?"
outRun="${outDir}/lactoserv/bin/run"

if (( ${#targets[@]} == 0 )); then
    if (( ${#lintArgs[@]} != 0 )); then
        targets+=(lint)
    fi
    if (( ${#runArgs[@]} != 0 )); then
        targets+=(run)
    fi
    if (( ${#targets[@]} == 0 )); then
        targets=(build)
    fi
fi

satisfy-all-targets "${targets[@]}" \
|| exit "$?"

if [[ " ${targets[*]} " =~ ' lint ' ]]; then
    # We don't lint inside `satisfy-all-targets`, because that would have the
    # build step capturing the run output (and indenting it, etc. etc.). So, we
    # just check here if that was a target, and use it to trigger the call-out.
    progress-msg
    progress-msg 'Linting...'
    lib node-project lint \
        --out="${outDir}" --src="${srcDir}" \
        "${lintArgs[@]}"
fi

if [[ " ${targets[*]} " =~ ' run ' ]]; then
    # Same deal as with `lint` above.
    progress-msg
    progress-msg 'Running the system...'
    exec "${outRun}" \
        --log-to-stdout \
        --config="$(base-dir)/etc/example-setup/config/config.mjs" \
        "${runArgs[@]}"
fi
