#!/bin/bash
#
# Copyright 2022-2023 the Lactoserv Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} [<opt> ...] <lint-arg> ...

    Runs the linter.

    --fix
      Fix whatever issues are fixable.
    --out=<dir>
      Directory where built output goes. Defaults to `out` directly under the
      main product directory.
'

# Perform fixes?
opt-toggle --var=doFix fix

# Built output directory.
opt-value --var=outDir out

# Arbitrary args to pass to the tool.
rest-arg --var=args args

process-args "$@" || exit "$?"


#
# Helper functions
#

# Finds a hopefully-unique file at the top level of the project whose name has
# the right prefix. Prints it.
function config-file-path {
    local configFile

    configFile=($(
        lib ls-files --output=lines \
            --cd="${srcDir}" --full-paths --depth=1 --include='^\.eslintrc'
    )) \
    || return "$?"

    if (( ${#configFile[@]} != 1 )); then
        if (( ${#configFile[@]} == 0 )); then
            error-msg 'Did not find a config file in the project!'
        else
            error-msg 'Did not find a _unique_ config file!'
        fi
        return 1
    fi

    echo "${configFile[0]}"
}

# Builds the linter if necessary, and then prints the path to it main binary.
function linter-path {
    local toolModule=linter
    local toolDir="${outDir}/${toolModule}"
    local toolPath="${toolDir}/bin/eslint"

    # Build the linter, if necessary.
    if [[ ! -x ${toolPath} ]]; then
        lib 1>&2 node-project build-main-module \
            --out="${outDir}" --modules-dir="${srcDir}" "${toolModule}" \
        || return "$?"
    fi

    echo "${toolPath}"
}


#
# Main script
#

srcDir="$(base-dir)/src"
outDir="$(lib buildy out-dir --out="${outDir}")" \
|| exit "$?"

configFile="$(config-file-path)" \
|| exit "$?"

toolPath="$(linter-path)" \
|| exit "$?"

opts=(
    --config "${configFile}"
    --max-warnings 0
)

if (( doFix )); then
    opts+=(--fix)
fi

if (( ${#args[@]} == 0 )); then
    # Run over all of the source by default.
    args=("${srcDir}")
fi

# TEMP!!!! FOR TESTING
sleep 1
info-msg '#################'
info-msg ">>${toolPath}<<" ">>${toolPath%/*}<<"
info-msg --exec ls -alF "${toolPath%/*}"
info-msg '#################'
(cd "${outDir}"; find 2>&1 . -name node_modules -prune -o -type f -print)
info-msg '#################'
sleep 1
# TEMP!!!! FOR TESTING

"${toolPath}" "${opts[@]}" -- "${args[@]}"
status="$?"

if (( ${status} == 0 )); then
    info-msg 'No linter errors! Yay!'
else
    error-msg --no-name 'Linter errors. Alas.'
    exit "${status}"
fi
