#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# This is an example prerequisite checker script.
#

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"

info-msg '#### HELLO FROM EXAMPLE PREREQ!'
