#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} [<opt> ...]

    Removes the build-output directory. This is just a convenient shorthand for
    `out-dir --remove`.

    --out=<dir>
      Directory where built output goes. Defaults to `out` directly under the
      main product directory.
'

# Built output directory.
opt-value --var=outDir out

process-args "$@" || usage --short


#
# Main script
#

lib . out-dir --out="${outDir}" --remove \
|| exit "$?"

progress-msg 'Clean!'
