#!/bin/bash
#
# Copyright 2022 the Lactoserv Authors (Dan Bornstein et alia).
# All code and assets are considered proprietary and unlicensed.

. "$(dirname "$(readlink -f "$0")")/lib/init.sh" || exit "$?"


#
# Argument parsing
#

function usage {
    print-usage $'
    Usage:

    ${name} [<opt> ...]
      Removes the build-output directory. This is just a convenient shorthand for
      `out-dir --remove`.

    --out=<dir>
      Directory where built output goes. Defaults to `out` directly under the
      main product directory.

    ${name} [--help | -h]
      Displays this message.
    '

    exit "$@"
}

# Want help?
opt-action --call='{ usage }' help/h

# Built output directory.
opt-value --var=outDir out

process-args "$@" || usage "$?"


#
# Main script
#

progress-msg --enable

lib out-dir --out="${outDir}" --remove \
|| exit "$?"

progress-msg 'Clean!'
