#!/bin/bash
#
# Copyright 2022 the Lactoserv Authors (Dan Bornstein et alia).
# This project is PROPRIETARY and UNLICENSED.

. "$(dirname "$(readlink -f "$0")")/lib/init.sh" || exit "$?"


#
# Argument parsing
#

function usage {
    print-usage $'
    Usage:

    ${name} [<opt> ...] [<file> ...]
      Fixes `package.json` files in various ways. With <file>s, processes only
      the indicated files; otherwise processes the entire source tree.

    ${name} [--help | -h]
      Displays this message.
    '

    exit "$@"
}

# Want help?
opt-action --call='{ usage }' help/h

# Specific paths to process
rest-arg --var=files --filter=/./ file

process-args "$@" || usage "$?"


#
# Helper functions
#

# The actual import-wrangling AWK script.
WRANGLER_AWK=$'
/ from ["\']/ {
    from = $0;
    sub(/^.* from [\'"]/, "", from);
    sub(/[\'"].*/, "", from);
    $0 = from;
    if (from ~ /^@this\//) {
        deps[from] = 1;
        #print from;
    }
}

END {
    count = 0;
    for (dep in deps) {
        count++;
        result[count] = dep;
    }

    sort(result);
    for (i = 1; i <= count; i++) {
        print result[i];
    }
}

# Good ole selection sort.
function sort(array, withLocals, i, j, size, tmp) {
    size = length(array);
    for (i = 1; i < size; i++) {
        for (j = i + 1; j <= size; j++) {
            if (array[i] > array[j]) {
                tmp = array[i];
                array[i] = array[j];
                array[j] = tmp;
            }
        }
    }
}
'

# Determines the proper intra-project dependencies under the given directory.
function get-deps {
    local srcDir="$1"
    local files

    info-msg '####### START DEPS' "${srcDir}"
    files=($(find "${srcDir}" -name '*.js'))
    awk "${WRANGLER_AWK}" "${files[@]}"
    info-msg '####### END DEPS'
}

# Runs the fixer on the given file.
function do-fix {
    local filePath="$1"

    local oldDeps
    oldDeps="$(jval <"${filePath}" --input=read '.dependencies // {}')"
    info-msg '############ OLD' "${oldDeps}"

    local foundDeps
    foundDeps="$(jarray --input=strings $(get-deps "$(dirname "${filePath}")"))"
    info-msg '############ FOUND' "${foundDeps}"

    jval \
        oldDeps:json="${oldDeps}" \
        foundDeps:json="${foundDeps}" '
    ($foundDeps | map({ key: ., value: "*" }))
    + ($oldDeps | with_entries(map(select(.key | startswith("@this") | not))))
    '
    info-msg '###### OK?'

    local pkg
    pkg="$(jval <"${filePath}" --input=read \
        dependencies:json="${oldDeps}" '
    {
        name: .name,
        version: .version,
        type: "module",
        private: true,
        license: "UNLICENSED",
        BLANK_LINE_1: "",
        exports: "./index.js",
        imports: {
          "#x/*": "./export/*.js",
          "#p/*": "./private/*.js"
        }
    }
    |
    if $dependencies == {}
    then .
    else . + {
        BLANK_LINE_2: "",
        dependencies: $dependencies
    }
    end
    ')"

    awk <<<"${pkg}" > "${filePath}" '
        /BLANK_LINE/ { print ""; next }
        { print; }
    '
}


#
# Main script
#

srcDir="$(base-dir)/src"

if (( ${#files[@]} == 0 )); then
    cd "${srcDir}"
    files=($(find . -name 'package.json'))
fi

for file in "${files[@]}"; do
    info-msg "Processing ${file}..."
    do-fix "${file}" || exit "$?"
done

info-msg ''
info-msg 'Done!'
