#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

#
# This is a top-level script dispatcher which dispatches to a command found in
# any of the units. It is named `ubik` for historical reasons.
#

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"


#
# Argument parsing
#

define-usage --with-help $'
    ${name} <command> [<subcommand> ...] [<opt> ...] [--] [<arg> ...]

    Run a subcommand. <opt>s and <arg>s depend on the specific subcommand.
'

# The main command.
positional-arg --var=cmdName command

# The actual command arguments.
rest-arg --var=args args

process-args "$@" || usage --short


#
# Main script
#

if [[ ${cmdName} == '' ]]; then
    lib helpy print-all-commands --prefix="$(this-cmd-name) "
    exit 1
fi

if declare -F "${cmdName}" >/dev/null 2>&1; then
    # It's actually a function from the library, not a separate command.
    "${cmdName}" "${args[@]}"
    exit "$?"
fi

lib "${cmdName}" "${args[@]}"
exitCode="$?"

if (( exitCode == 127 )); then
    # Print out top-level help, if it looks like this exit code was due to the
    # `lib` command itself not finding the command.
    if ! lib --path --quiet "${cmdName}"; then
        error-msg "Command not found: ${cmdName}"
        error-msg
        lib helpy print-all-commands --prefix="$(this-cmd-name) "
    fi
fi

exit "${exitCode}"
