#!/bin/bash
#
# Copyright 2022-2023 the Bashy-lib Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

. "$(dirname "$(readlink -f "$0")")/_init.sh" || exit "$?"
. "$(this-cmd-dir)/timey-help.sh"


#
# Argument parsing
#

define-usage $'
    ${name} [<opt> ...] <time> [+<format>]

    Prints a given time value, optionally using the format given (same syntax as
    `date`). With no format given, prints using the system default date format.

    --input=<type> :: rfc822 secs
      Indicates the format of the given <time>.
      `secs` -- A number of seconds since the Unix Epoch, or, as a special case,
        `now` to mean the current moment. This is the default.
      `rfc822` -- A string in RFC822 format.
    --utc
      Produce output for the UTC time zone.

    ${name} [--help | -h]

    Displays this message.
'

# Want help?
opt-action --call='{ usage; exit }' help/h

# Input type.
opt-value --var=inputType --init='secs' --enum='secs rfc822' input

# UTC?
opt-toggle --var=utc utc

# Time value to parse.
positional-arg --required --var=time time

# Output format.
positional-arg --var=format --filter='/^[+]/' format

process-args "$@" || usage --short


#
# Main script
#

if [[ ${format} == '' ]]; then
    formatArg=()
else
    formatArg=("${format}")
fi

if (( utc )); then
    utcOpt=('--utc')
else
    utcOpt=()
fi

timeSecs="$(timey-parse "${inputType}" "${time}")" \
|| exit "$?"

timey-format "${utcOpt[@]}" "${timeSecs}" "${formatArg[@]}"
