# Copyright 2022-2023 the Lactoserv Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

name: Lint / Build / Test

# Controls when the workflow will run.
on:
  # Triggers the workflow on push or PR events for the branch `main`.
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel.
jobs:
  # This workflow contains a single job called `build`.
  build:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the
    # job.
    steps:
      - name: Get Node.
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Note: Checks out into $GITHUB_WORKSPACE, which is also the CWD.
      - name: Clone repo.
        uses: actions/checkout@v3

      - name: Run the linter.
        run: ./scripts/lint

      - name: Actually build.
        run: ./scripts/build --make-distro

      - name: Run the unit tests.
        run: ./scripts/run-tests

      - name: Ensure the cert creator still works.
        run: ./scripts/make-localhost-cert

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo THIS IS ALSO
      #    echo A TEST.
      #    echo "Workspace: ${GITHUB_WORKSPACE}"
      #    ls -alF "${GITHUB_WORKSPACE}"
      #    pwd
