# Copyright 2022-2024 the Lactoserv Authors (Dan Bornstein et alia).
# SPDX-License-Identifier: Apache-2.0

name: Lint / Build / Test

# Controls when the workflow will run.
on:
  # Triggers the workflow on push or PR events for the branch `main`.
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Workflow. Jobs run in parallel by default, but that is moot here: there's only
# one job.
jobs:
  # Build the project!
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Node.
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Note: Checks out into `$GITHUB_WORKSPACE`, which is also the `$CWD`.
      - name: Clone repo.
        uses: actions/checkout@v4

      - name: Run the linter.
        run: ./scripts/ubik lint

      - name: Actually build.
        run: ./scripts/ubik build --make-distro

      - name: Run the unit tests.
        run: ./scripts/ubik run-tests

      - name: Ensure the cert creator still works.
        run: ./scripts/ubik make-localhost-cert

      #- name: Run a multi-line script.
      #  run: |
      #    echo THIS IS
      #    echo A TEST.
      #    echo "Workspace: ${GITHUB_WORKSPACE}"
      #    ls -alF "${GITHUB_WORKSPACE}"
      #    pwd

  # Build the project!
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Node.
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      # Note: Checks out into `$GITHUB_WORKSPACE`, which is also the `$CWD`.
      - name: Clone repo.
        uses: actions/checkout@v4

      - name: Build.
        run: ./scripts/ubik build --make-distro

      - name: Run the integration tests.
        run: ./scripts/ubik run-tests --type=integration
